router_id: 10.0.0.2
interfaces:
  Ethernet1: { ip: 10.1.2.1/30, description: "p2p_leaf1" }
  Ethernet2: { ip: 10.1.2.5/30, description: "p2p_leaf2" }
  Ethernet3: { ip: 10.1.2.9/30, description: "p2p_leaf3" }
  Ethernet4: { ip: 10.1.2.13/30, description: "p2p_leaf4" }
