router_id: 10.0.0.1
interfaces:
  Ethernet1: { ip: 10.1.1.1/30, description: "p2p_leaf1" }
  Ethernet2: { ip: 10.1.1.5/30, description: "p2p_leaf2" }
  Ethernet3: { ip: 10.1.1.9/30, description: "p2p_leaf3" }
  Ethernet4: { ip: 10.1.1.13/30, description: "p2p_leaf4" }
bgp_neighbors:
  - ip: 10.1.1.2
    remote_as: 65101
    description: LEAF-01
